apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xavr5fjqz-python
  janus-idp.io/tekton: xavr5fjqz-python
  backstage.io/kubernetes-id: xavr5fjqz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xavr5fjqz-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
