apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xavr5fjqz-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-7d8a5200cc.79x4.p3.openshiftapps.com/rhtap/rhtap-qe:b9ede674dbe37d7dcf7763316c1785be2c3a49e4@sha256:7f78fe1da8a8ac25a1359a2687b58d1902fa719dcce082df4ed16718b1a65a3a
          name: container-image
